### ISSUE TITLE
Android V2 embedding

### ISSUE THREAD

**Issue by xarmat** [inway/flutter_ringtone_player#25]
The plugins `flutter_ringtone_player` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

In release sdk 2.5.0

**Comment by aarajput** [comment]
@xarmat ! I have fixed this issue in P.R https://github.com/inway/flutter_ringtone_player/pull/26.

You can use below in your pubspec.yaml until this p.r is resolved.

```
dependency_overrides:
  flutter_ringtone_player:
    git:
      url: https://github.com/aarajput/flutter_ringtone_player.git
      ref: 'issue/android_v2_embedding'
```
